apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-arxiv-app

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml

generatorOptions:
  disableNameSuffixHash: true
