apiVersion: v1
kind: Service
metadata:
  name: query-service-lb
  namespace: rag-arxiv-app
spec:
  type: LoadBalancer
  selector:
    app: query-service
  ports:
    - protocol: TCP
      port: 80       # external port on the LoadBalancer
      targetPort: 80 # container port