apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-arxiv-app

resources:
  - vector-db-deployment.yaml
  - vector-db-service.yaml
  - weaviate-deployment.yaml
  - weaviate-service.yaml
  - weaviate-pvc.yaml

secretGenerator:
  - name: vector-db-env
    envs:
      - vector_db_service.env

generatorOptions:
  disableNameSuffixHash: true