services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always

  rag_arxiv_indexing_service:
    build:
      context: .
      dockerfile: indexing/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - indexing/.env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis