global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "index_service"
    static_configs:
      - targets: ["index_service:80"]

  - job_name: "query_service"
    static_configs:
      - targets: ["query_service:80"]