apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: index-service
  template:
    metadata:
      labels:
        app: index-service
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: index-service
          image: 633605692921.dkr.ecr.eu-central-1.amazonaws.com/index-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: index-service-env
          volumeMounts:
            - name: pdf-storage
              mountPath: /app/data/pdfs
      volumes:
        - name: pdf-storage
          persistentVolumeClaim:
            claimName: pdf-storage-pvc