apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-arxiv-app

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml

secretGenerator:
  - name: index-service-env
    envs:
      - index_service.env

generatorOptions:
  disableNameSuffixHash: true