apiVersion: v1
kind: Service
metadata:
  name: index-service-lb
  namespace: rag-arxiv-app
spec:
  type: LoadBalancer
  selector:
    app: index-service       # connects to the pods
  ports:
    - port: 80               # external port on ELB
      targetPort: 80         # pod container port
